apiVersion: v1
kind: Service
metadata:
  name: socket-chat-ext-service
spec:
  selector:
    app: chat-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000