apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-chat-app
  labels:
    name: socket-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-chat-app
  template:
    metadata:
      labels:
        app: socket-chat-app
    spec:
      containers:
        - name: socket-chat-app
          image: cashelbloom/socket-chat-app
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: message-db-secret
                  key: message-db-root-use
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: message-db-secret
                  key: message-db-root-pw
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: message-db-configmap.yaml
                  key:  message-db-url
