apiVersion: v1
kind: Service
metadata:
  name: socket-chat-ext-service
spec:
  selector:
    app: socket-chat-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5432
      nodePort: 30000